### ISSUE TITLE
YouTube images on browse are blurry

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-csv#1]
I think it's using the thumb version ...

**Comment by evanwill** [comment]
it uses what ever you put in image_small or image_thumb in the csv, there is no youtube logic in the template

**Comment by dcnb** [comment]
I get that better now. In the example data, which most people will likely
follow, the images end up being blurry. So maybe just adjust that.

I also wonder about going away from youtube. I get it, but the parsing of
youtube links seems potentially risky. It might be the best solution; I'm
just wondering if its sustainable. And if there are a limited number of
options to support, maybe making options for each would be good, or using
object_template and object_download more explicitly.
