### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by shawngraham** [CollectionBuilder/collectionbuilder-csv#24]
Very interested to give this a whirl; love the idea! Great work.

Can't get it to build though. Followed the 'brief overview' directions, also consulting the docs, to use the template. Changed the config with my own site settings to use with gh pages, used the demo metadata template and added one line of info; the build fails every time. The error message from github is not useful; just says page failed, so I'm a bit baffled. I am not very familiar with troubleshooting jekyll.

my repo: https://github.com/shawngraham/test-collectionbuilder 

my metadata file: https://github.com/shawngraham/test-collectionbuilder/blob/main/_data/demo-sg.csv

my config: 

```
# site domain, full URL to the production location of your collection
url: https://shawngraham.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /test-collectionbuilder
# location of code, the full url to your github repository
source-code: https://github.com/shawngraham/test-collectionbuilder
```

followed eventually with:

```
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: demo-sg
```

**Comment by evanwill** [comment]
@shawngraham thanks for giving it a whirl! 
Your demo repository and metadata look correct, and it will build locally using Jekyll--however collectionbuilder-csv can't be built using standard GitHub Pages build (it uses plugins and a more up-to-date version of Jekyll)--so the build just fails. 

You can use [collectionbuilder-gh](https://github.com/CollectionBuilder/collectionbuilder-gh) template with standard GH pages, or you can [set up a GitHub action to build your CSV version](https://collectionbuilder.github.io/cb-docs/docs/deploy/actions/).

Let us know how it goes!

**Comment by dcnb** [comment]
And another way to build it (easier than GitHub actions) is to use Render
-->
https://collectionbuilder.github.io/cb-docs/docs/deploy/thirdparty/#deploy-using-render

Just sign up, connect your repository, change the couple settings and
Render will build and host the site for free at an onrender.com site. And
despite what Evan might say, I am not a sales rep for Render -- I just
really like they're platform :)

Thanks so much for trying CollectionBuilder, @shawngraham
<https://github.com/shawngraham>

**Comment by dcnb** [comment]
THEIR, not they're.  ARGH. And now it's saved forever in GitHub ...

**Comment by shawngraham** [comment]
ah, gotcha! thanks @evanwill @dcnb I'll give both of those workflows a try.

**Comment by evanwill** [comment]
ha ha, @dcnb still not sure how logging into another service, clicking a bunch of buttons over there and linking things up is easier than adding a single YAML file to your repository? 😉 😉

**Comment by shawngraham** [comment]
ok, an update - i tried both the workflow, and the Render thingy.

Both were quite easy. However, with the workflow, the workflow would run, but the site would still not deploy. With render, it deployed, but was broken. The log file for Render showed an interesting error:

```
Error cb_helpers: Item for featured image with objectid 'demo_001' not found in configured metadata 'demo-sg'. Please check 'featured-image' in '_data/theme.yml'
```
 In my metadata file, I had deleted a few of the items. So, I changed the featured image in the _data/theme.yml to the image that I had added to the metadata (demo_008) and lo! and behold! the github action worked.

So there we go. One thing - since I added the action, and the workflow was deploying to a new branch, I had to update the pages settings to load from that branch. Anyway, very cool!

**Comment by evanwill** [comment]
Oh okay thanks for the update @shawngraham that's helpful-- that is weird/frustrating that the CB warning message is actually causing the GitHub Action and Render to not build it! That is intended to be a helper when you are working locally, and it doesn't interrupt the build, so not sure why the Action is taking those messages as an error and exiting. I will have to look into that...
