### ISSUE TITLE
cb_helper warning messages cause automated build to exit

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-csv#25]
... investigate?

e.g. 
`Error cb_helpers: Item for featured image with objectid 'demo_001' not found in configured metadata 'demo-sg'. Please check 'featured-image' in '_data/theme.yml'`
seems to cause failed build.

**Comment by dcnb** [comment]
@evanwill You know, I have seen errors for keeping watch -- one that's a
warning that says;

Notice cb_page_gen: record '83' in 'keepingwatch', 'indian-mica-' is being
sanitized to create a valid filename. This may cause issues with links
generated on other pages. Please check the naming convention used in
'objectid' field.

But it doesn't break the render build. It might just be a certain kind of
error?

**Comment by evanwill** [comment]
yeah actually, I can't see what was breaking it... it doesn't seem to be the CB helper notices
