### ISSUE TITLE
page_gen: 

### ISSUE THREAD

**Issue by sgraham3** [CollectionBuilder/collectionbuilder-csv#34]
I have tested both metadata_one and metadata_two and they both build on there own.  When I uncomment and add the data names as the readme states, it builds with no errors and the site is empty.  I have tried multiple combinations of commenting and adding with no luck. 
Does the metadata: need to be commented out? 

# [optional: only used if you need to tweak CB defaults or generate from more than one data file]:
page_gen:
  - data: 'metadata_one'
  - data: 'metadata_two'

**Comment by sgraham3** [comment]
Thanks for fast and detailed response.  I defiantly misunderstood what the page_gen was doing. I was trying to pull both csv files into one collection. Seemed like a good idea(easier to manage) to have separate csv for different types-formats.

**Comment by evanwill** [comment]
@sgraham3 yeah--I am thinking about that option now too and seeing if there is a way to cleanly build it into the template with out making anything too complicated! It would also be nice to for your type of use case to just set multiple in the `metadata` value (if you don't need to customize page_gen). The problem being we try to keep CB-GH options interchangeable with CB-CSV, and it would be hard to build into GH. 

For now I tried to clarify a bit in the [doc page](https://github.com/CollectionBuilder/collectionbuilder-csv/blob/main/docs/plugins.md) the current limitations.

**Comment by sgraham3** [comment]
@evanwill I think it would be a good idea but see how it may be overly complicated or not needed for most users needs. I am using cb it a little differently. 

- I maintain cemeteries in gis mapping and export to the csv as updated. 
- I also have other objects that are separate from the gis (photos, etc )

The up dated docs defiantly clarify and explain much better, Thanks

**Comment by evanwill** [comment]
closing this, and opening a feature issue #35 to think about!
Thanks @sgraham3
