### ISSUE TITLE
compound object stuff to do

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-csv#37]
metadata and docs:

- [x] replace demo data with public domain items, sensible compound objects
- [ ] think through convention for talking about compound objects/items
- [x] update/improve item include comments
- [x] compound parent items seem like they shouldn't have format or type generally (rather than making up non-standardized value)
- [ ] recheck [docs](https://github.com/CollectionBuilder/cb-docs/pull/22) with everything set

test with extreme demo metadata:

- [x] check button groups to see if they work/fix reasonably on mobile (they don't wrap, so can look weird or x overflow)
- [x] handling of labels when compound item doesn't have a title

bugs:

- [x] clean up modal sizing, odd more margin on right side issue on mobile
- [x] recheck cb_page_gen and cb_helpers to make sure they are working as expected with compound stuff
- [x] cb_helpers fix logic in featured image
- [x] check svg icons odd alignment issue, .timeline-thumb width 100%
- [x] compound modal stretched link check other card bits
- [x] browse js icons
- [x] data derivatives links and objects
- [x] text align in item modals
- [x] .compound-thumb has `height: 110px; max-width:90%` ends up changing aspect ration of images, need one or the other, or both as max-? i think just change to max-height: 110px;
- [x] reference link on compound child uses title as hash rather than id _includes/item/child/citation-box.html
- [x] arrow key use with gallery open can end up with odd results, seems to go through all item hashs, not just ones in the gallery

tech improvements:

- [x] check default metadata filter used, if does not have parentid and does have objectid, make into an include
- [x] fix map-js console errors with getPopup, avoid extra marker creation with markerOneOff thing
- [x] fix arrow key confusion in compound item modal (arrow click goes to next item instead of object) ?
- [x] potential of some workaround to avoid the two different id # hashes used for the modal (external link + next button)

**Comment by jawalsh** [comment]
Perhaps something else for the list…

If one chooses an image from a compound object as the "featured image," the "featured image" link on the homepage is broken because it's generating a URL like `https://biblicon.org/cbp/items/cbp_003.html` (which doesn't exist) rather than   `https://biblicon.org/cbp/items/cbp_001.html#cbp_003` (which does exist).

**Comment by evanwill** [comment]
thanks @jawalsh, that issue is fixed now, if you want to use it right now in your projects, swap out "_plugins/cb_helpers.rb" with the [updated version](https://github.com/CollectionBuilder/collectionbuilder-csv/blob/compound-objects/_plugins/cb_helpers.rb). But heads up, there is a bunch of other pretty critical fixes still rolling out (like the search links were broken!), so might want to wait to update everything once this PR is merged.

**Comment by dcnb** [comment]
"compound parent items seem like they shouldn't have format or type generally (rather than making up non-standardized value)"

This seems arbitrary -- it's still an item, a record has a format and type. We should keep this convention.

**Comment by dcnb** [comment]
"check button groups to see if they work/fix reasonably on mobile (they don't wrap, so can look weird or x overflow)"

I checked with extreme circumstances. They break across words and look fine.

**Comment by evanwill** [comment]
this is merged, closing this. Docs tasks moved to https://github.com/CollectionBuilder/cb-docs/issues/33
