### ISSUE TITLE
Links to items from data.html not working

### ISSUE THREAD

**Issue by jawalsh** [CollectionBuilder/collectionbuilder-csv#39]
Using the compound objects branch, the links to items from data.html don't seem to be working. They are not include the baseurl variable in the link. Here is an example: <https://biblicon.org/cbp/data.html>. All the other URLs on the site seem to be fine and include the baseurl.

**Comment by dcnb** [comment]
Hey @jawalsh! Looks like that is my fault ... And @evanwill  fixed the issue in the branch five days ago. I'm going to never live this down ... 

If you look at Evan's commit, you can see the edit he made: 

https://github.com/CollectionBuilder/collectionbuilder-csv/commit/60f6bef20623d2c4465a90f009e0e8ee9665d46c

So if you replace your repostory's /assets/js/metadata.min.json file with this one, the links should work. 

My apologies!

**Comment by dcnb** [comment]
Here's the link I didn't include, with the corrected table data file: 

https://github.com/CollectionBuilder/collectionbuilder-csv/blob/compound-objects/assets/js/metadata.min.json

**Comment by evanwill** [comment]
@jawalsh there is still quite a few bugs we are working on listed in #37 (several like this one related to removing relative_url in various places!). Once it gets sorted out, we can help you update your project--but feel free to keep working, since the data structure and basic look will be the same.

**Comment by jawalsh** [comment]
Great! Thank you both, @evanwill and @dcnb. I'll update that file and keep going.
