### ISSUE TITLE
add "alt_text" field for use in template

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-csv#50]
the template uses title or description for alt text of collection images which may or may not be appropriate for all collections. We could add "alt_text" as a technical field (like object_template, image_small, image_thumb) that suggests users fill the "alt" field with appropriate alt text for each item--either by doing full description or generating it from existing metadata fields as necessary for each type of item. 
This would allow the template to use alt text with more confidence, allow users to generate it using a variety of methods appropriate to the various item in their collection, and forefront the necessity of this descriptive work (which is often missing from archival metadata). 

in the template it could look like `alt="{{ item.alt | default: item.description | default: item.title }}"`

- [x] add "alt_text" column to demo metadata
- [x] replace alt values in template
- [x] check iframe titles and other similar values
- [x] add to metadata template
- [x] document use
- [x] update Google Sheet versions of template metadata

**Comment by dcnb** [comment]
Good idea! After team meeting, decided to pursue after merge of new CSV compound item branch

**Comment by evanwill** [comment]
in "alt-text-field" branch
