### ISSUE TITLE
Issue templates, code of conduct etc.

### ISSUE THREAD

**Issue by maehr** [CollectionBuilder/collectionbuilder-csv#57]
I'd love to add some features to this repo:

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- Improved README.md
- SECURITY.md 
- Issue & PR templates

PS: Here's a full fledged example <https://github.com/maehr/github-template> of these things.

**Comment by evanwill** [comment]
Thank you for bringing this up @maehr! 
Some of the community docs are located in different locations (and apparently not linked to): 

- [code of conduct](https://github.com/CollectionBuilder/collectionbuilder.github.io/blob/main/CODE_OF_CONDUCT.md) in the central org website repo
- [contributing](https://github.com/CollectionBuilder/collectionbuilder.github.io/blob/main/CONTRIBUTING.md) in the central org website repo
- [change log](https://collectionbuilder.github.io/cb-docs/docs/changes/) is a section of the docs

Do you think we should have a copy of each document in every CB repository or does it make sense to keep a central copy and link to it?
 
What are you thinking about for improving the README? Basically just ensuring that the [template sections](https://github.com/maehr/github-template/blob/main/README.template.md) are covered?

**Comment by maehr** [comment]
I'm a big fan of standalone repos. Redundancy helps regarding SEO, GitHub Insights <https://github.com/CollectionBuilder/collectionbuilder-csv/community> and is in accordance with <https://endings.uvic.ca/principles.html>.

The readme could be a bit more detailed about the CB ecosystem and the roadmap (which is helpful for both newbies and pros). Don't you think?

**Comment by maehr** [comment]
PS: Issue and PR templates are very helpful for maintainers and contributors alike. They help structuring and triaging ideas: https://github.com/maehr/github-template/issues/new/choose or more specifically https://github.com/maehr/open-data-template/issues/new/choose

**Comment by evanwill** [comment]
I added in the CODE_OF_CONDUCT.md and CONTRIBUTING.md from the central project. @juliastone0729 is reviewing the code of conduct to see if we should work on any updates--let us know if you have specific resources worth looking at for that, beyond your [template example](https://github.com/maehr/github-template/blob/main/CODE_OF_CONDUCT.md).

@maehr what do you think would be in SECURITY.md for a project like this? Basically just providing a contact? 
@maehr would you like to work on a draft of the Issue templates? I think it is a good idea to provide some structure, but also need to balance it with turning away novice users (which is our audience)--we want to make sure it is welcoming.

**Comment by maehr** [comment]
@evanwill I would love to work on a draft for the issues. I will open a PR shortly. For the `SECURITY.md` a contact method will suffice IMHO.

**Comment by evanwill** [comment]
closing as completed
